// Regenerates the checked-in ora contract artifacts from a served OpenAPI
// spec: src/contract/types.gen.ts (TypeScript types for every published
// schema) and src/contract/version.ts (the contract version the build is
// pinned against). CI regenerates from production and fails on any diff, so
// a contract bump on ora.ai turns into a red build here instead of a user
// bug report.
//
// Usage:
//   pnpm contract:gen                     # production spec (the default)
//   pnpm contract:gen --url http://localhost:4214/api/openapi.json
//
// Output is deterministic for a given spec - no timestamps, no source URL -
// so the drift check is a plain `git diff --exit-code`.

import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
// v6 on purpose: v7 peers on the TypeScript compiler API, which this repo's
// TypeScript 7 (native port) does not expose. v6 is self-contained.
import openapiTS from "openapi-typescript";

const DEFAULT_SPEC_URL = "https://ora.ai/api/openapi.json";

const urlFlag = process.argv.indexOf("--url");
const specUrl =
	urlFlag !== -1 && process.argv[urlFlag + 1] ? process.argv[urlFlag + 1] : DEFAULT_SPEC_URL;

const res = await fetch(specUrl, { headers: { accept: "application/json" } });
if (!res.ok) {
	console.error(`contract:gen: ${specUrl} answered HTTP ${res.status}`);
	process.exit(1);
}
const spec = await res.json();

const version = spec?.info?.version;
if (!/^\d+\.\d+\.\d+$/.test(version ?? "")) {
	console.error(`contract:gen: spec info.version is not SemVer: ${JSON.stringify(version)}`);
	process.exit(1);
}

const types = await openapiTS(spec);

const header = [
	"// Generated by scripts/contract-gen.mjs - do not edit.",
	"// Regenerate: pnpm contract:gen [--url <openapi.json url>]",
	"",
].join("\n");

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = join(root, "src", "contract");
await mkdir(outDir, { recursive: true });

await writeFile(join(outDir, "types.gen.ts"), `${header}${types}`);
await writeFile(
	join(outDir, "version.ts"),
	[
		header,
		"/** The ora contract version (spec info.version) these types were generated from. */",
		`export const BUILT_AGAINST = "${version}";`,
		"",
	].join("\n"),
);

console.log(`contract:gen: wrote src/contract/ for contract ${version}`);
